name: Terraform GitHub Actions

on:
  push:
    branches:
      - test
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 'latest'

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Install TFLint
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Install and Run TFLint
      run: |
        curl -sL https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip -o tflint.zip
        unzip tflint.zip
        chmod +x tflint
        ./tflint --version
        ./tflint

    - name: Push to Dev Branch
      if: success()
      run: |
        git checkout -b dev
        git merge main
        git push origin dev

    # - name: Trigger TFC Webhook
    #   run: |
    #     curl -X POST -H "Content-Type: application/json" -d '{"payload": {"some": "data"}}' ${{ secrets.TFC_WEBHOOK_URL }}
